package com.mpls;
import java.util.*;

public class Game {
    public int startGame(){
        Scanner scanner = new Scanner(System.in);
        System.out.println("Hello and welcome to Dre's Rock Paper Scissors Game!");

        //start game

        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)

        // create a variable to hold the cpu response generated by the getCPUResponse() method.

        //compare user and cpu response with each other to decide the winner.
        return ;
    }

    public int getCPUResponse(){
        // Generate random integers in range 1 to 3
        Random g = new Random();
        int response = g.nextInt(3);
        return response;
    }
}

